/**
 * Samples a world GeoJSON on a lat/lon grid and writes the land points out as a
 * compact array, so the 3D globe ships real continents without loading a map
 * image at runtime.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const geo = JSON.parse(readFileSync(new URL('./world.geojson', import.meta.url), 'utf8'))

// Flatten to [{ bbox, rings }] where a ring is [[lon, lat], …]
const shapes = []
for (const feature of geo.features) {
  const g = feature.geometry
  if (!g) continue
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : []
  for (const poly of polys) {
    const outer = poly[0]
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
    for (const [x, y] of outer) {
      if (x < minX) minX = x
      if (x > maxX) maxX = x
      if (y < minY) minY = y
      if (y > maxY) maxY = y
    }
    shapes.push({ bbox: [minX, minY, maxX, maxY], rings: poly })
  }
}

function inRing(x, y, ring) {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]
    const [xj, yj] = ring[j]
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside
  }
  return inside
}

function isLand(lon, lat) {
  for (const { bbox, rings } of shapes) {
    if (lon < bbox[0] || lon > bbox[2] || lat < bbox[1] || lat > bbox[3]) continue
    if (!inRing(lon, lat, rings[0])) continue
    let hole = false
    for (let i = 1; i < rings.length; i++) {
      if (inRing(lon, lat, rings[i])) {
        hole = true
        break
      }
    }
    if (!hole) return true
  }
  return false
}

// Even-area sampling: step longitude proportionally to 1/cos(lat) so dots don't
// bunch up at the poles.
const LAT_STEP = 2.2
const points = []
for (let lat = -56; lat <= 78; lat += LAT_STEP) {
  const circumference = Math.cos((lat * Math.PI) / 180)
  const lonStep = circumference > 0.06 ? LAT_STEP / circumference : 360
  for (let lon = -180; lon < 180; lon += lonStep) {
    if (isLand(lon, lat)) points.push(Math.round(lat * 10), Math.round(lon * 10))
  }
}

const out = `/**
 * Land points for the 3D globe — generated by sampling a world GeoJSON on an
 * equal-area lat/lon grid. Flat array of tenths of a degree: [lat, lon, …].
 * Regenerate with scripts/sample-land.mjs if you change the density.
 */
export const LAND_POINTS = new Int16Array([${points.join(',')}])
`

writeFileSync(new URL('../src/data/landPoints.js', import.meta.url), out)
console.log(`${points.length / 2} land dots, ${(out.length / 1024).toFixed(1)} KB`)
